### PR TITLE
Added folder with txt

### PR DESCRIPTION
**Pull request by HmelDA**
Added folder with txt because PyCharm didn't see an empty folder

### CODE REVIEW

**Comment by riassale** [comment]
@HmelDA  Hi. Could you please provide me an email?

**Comment by HmelDA** [comment]
> @HmelDA Hi. Could you please provide me an email?

Hi, sure)
hmeldma@gmail.com

**Comment by riassale** [comment]
@HmelDA  Could you send the EPAM email instead?

**Comment by HmelDA** [comment]
> @HmelDA Could you send the EPAM email instead?

dmitrii_khmelinin@epam.com

**Pull request merged**
